spring.application.name=quan_ly_thuc_tap

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/internshipdb
spring.datasource.username=postgres
spring.datasource.password=Ngocmai@1004

spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

service.jwt.secret-key=VGxhbmRJbnRlcm5zaXBoaXAtSldULVNlY3JldC1LZXktMjAyNi1Mb25n
service.jwt.expiration=604800000
service.jwt.refresh-expiration=604800000 

spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true